### ISSUE TITLE
Error : Ps_Modification_coors_hek_complete.txt File Missing. 

### ISSUE THREAD

**Issue by DattaSujayAyyagari** [Janga-Lab/Penguin#2]
Greetings, 

I am trying to use Penguin tool for predicting modifications in Sars-Cov-2 Virus. I am getting the following error after running the tool. 

**Input :**
module load python/3.9.8
module load cudatoolkit
module load minimap
module load gnu/9.3.0
module load samtools

python main.py -r /Downloads/sars-cov-2/GCF_009858895.2_ASM985889v3_genomic.fna -f /Downloads/sars-cov-2/reads.fastq

**Output :** 
M::mm_idx_gen::0.042*0.23] collected minimizers
[M::mm_idx_gen::0.044*0.26] sorted minimizers
[M::main::0.044*0.26] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.044*0.26] mid_occ = 10
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.045*0.27] distinct minimizers: 5587 (99.93% are singletons); average occurrences: 1.004; average spacing: 5.332; total length: 29903
[M::worker_pipeline::0.078*0.52] mapped 4000 sequences
[M::worker_pipeline::0.087*0.56] mapped 4000 sequences
[M::main] Version: 2.26-r1175
[M::main] CMD: minimap2 -ax map-ont --split-prefix /tmp/temp_name /Downloads/sars-cov-2/GCF_009858895.2_ASM985889v3_genomic.fna /Downloads/sars-cov-2/reads.fastq
[M::main] Real time: 0.088 sec; CPU: 0.050 sec; Peak RSS: 0.008 GB
error: could not open reads.fastq for read
error: could not load the index files for input file reads.fastq
Please run nanopolish index on your reads (see documentation)
Input the bed filename with its extension:Traceback (most recent call last):
  File "/Downloads/gen_coors.py", line 45, in <module>
    filename = input("Input the bed filename with its extension:") 
EOFError: EOF when reading a line
2024-02-05 22:46:05.022807: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /N/soft/rhel8/python/gnu/3.9.8/lib:/N/soft/rhel8/sqlite/gnu/3.35.5/lib:/N/soft/rhel8/mvapich/gnu/2.3.5/lib:/N/soft/rhel8/gcc/9.3.0/lib64:/N/soft/rhel8/gcc/9.3.0/lib:/N/soft/rhel8/minimap/gnu/2.26/lib:/N/soft/rhel8/cuda/12.2/nvvm/lib64:/N/soft/rhel8/cuda/12.2/lib64:/opt/thinlinc/lib64:/opt/thinlinc/lib
2024-02-05 22:46:05.022921: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/Downloads/SVM.py", line 17, in <module>
    df1 = pd.read_csv("Ps_Modification_coors_hek_complete.txt",sep=' ',skiprows=(0),header=(0))#Pseu_Modification_coors_ns_hek.txt
  File "/N/soft/rhel8/python/gnu/3.9.8/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/N/soft/rhel8/python/gnu/3.9.8/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/N/soft/rhel8/python/gnu/3.9.8/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/N/soft/rhel8/python/gnu/3.9.8/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/N/soft/rhel8/python/gnu/3.9.8/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/N/soft/rhel8/python/gnu/3.9.8/lib/python3.9/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'Ps_Modification_coors_hek_complete.txt'

**Comment by hsdoaa** [comment]
Hello,

It looks that the Ps_modification_coors_complete.txt was not generated by gen_coors.py. This might be due to not able to generate the sam file from mapping fastq files to reference genome or you did not enter the bed file name with the absolute path and extension when you get the message "Input the bed filename with its extension:". Also, make sure to include the fast5 files folder (fast5_files) from which reads.fastq file was generated in the same path of main.py as I see you got the message:
could not open reads.fastq for read

Hope this helps.

Doaa
